
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  apachehttpd:
    image: twistedbytes/centos9-apachehttpd:latest
    platform: linux/amd64
    networks:
      backend:
        aliases:
          - dockertest1.tbdocker.xyz
    depends_on:
      - php-fpm
      - db
    environment:
      - _TB_UIDGID_FROMDIR=/var/www/html/public
    volumes:
      # - ./docker-config/apache-vhosts:/etc/httpd/vhosts.d
      - ./docker-logs/httpd:/var/log/httpd
      - ./src/public:/var/www/html/public
    ports:
      - "127.0.0.1:${HTTP_PORT:-80}:80"
      - "127.0.0.1:${HTTPS_PORT:-443}:443"

  php-fpm:
    image: twistedbytes/centos9-phpfpm81:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      backend:
    environment:
      - _TB_INSTALL_PACKAGES=php-pecl-xdebug3
      - _TB_UIDGID_FROMDIR=/var/www/html
      - _TB_PHPFPM=Y
    volumes:
      - ./docker-logs/phpfpm:/var/log/php-fpm
      - ./docker-config/php/zz-xdebug.ini:/etc/php.d/16-xdebug.ini
      - ./src:/var/www/html

  php-cli:
    image: twistedbytes/centos8-phpfpm81
    restart: "no"
    networks:
      backend:
    environment:
      - _TB_UIDGID_FROMDIR=/var/www/html
      - _TB_SUDO_TOFROMDIR=Y
    volumes:
      - ./docker-logs/phpfpm:/var/log/php-fpm
      - ./src:/var/www/html

  db:
    image: mariadb:10.7
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # mailhog to send mail without sending them out to the internet
  # connect to http://localhost:8025
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    networks:
      - backend
    ports:
      - "127.0.0.1:8025:8025"

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - backend


volumes:
  database:
