version: "3.7"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  php:
    extends:
      file: compose-services.yml
      service: php
    networks:
      backend:
    environment:
      - _TB_Z=${TIMEZONE}
    volumes:
      # - ./docker-config/apache-vhosts:/etc/httpd/vhosts.d
      # - ./test/logs/httpd:/var/log/httpd
      # - ./src/Silverstripe:/var/www/html/Silverstripe
      - ./test/html:/var/www/html
#    command:
#      - php-fpm
#      - -F
#      - -O
