version: "3.7"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  apachehttpd:
    image: twistedbytes/centos9-apachehttpd:latest
    platform: linux/amd64
    networks:
      backend:
        aliases:
          - dockertest1.tbdocker.xyz
    depends_on:
      - php-fpm
      - db
    environment:
      - _TB_UIDGID_FROMDIR=/var/www/html
    volumes:
      # - ./docker-config/apache-vhosts:/etc/httpd/vhosts.d
      - ./docker-logs/httpd:/var/log/httpd
      - ./src:/var/www/html
    ports:
      - "127.0.0.1:${HTTP_PORT:-80}:80"
      - "127.0.0.1:${HTTPS_PORT:-443}:443"

  php-fpm:
    image: twistedbytes/centos9-phpfpm82:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      backend:
    environment:
      - _TB_UIDGID_FROMDIR=/var/www/html
      - _TB_PHPFPM=Y
      # - _TB_INSTALL_PACKAGES=php-pecl-xdebug3

      - SS_DATABASE_CLASS=MySQLDatabase
      - SS_DATABASE_SERVER=db
      - SS_DATABASE_USERNAME=root
      - SS_DATABASE_PASSWORD=root
      - SS_DATABASE_NAME=silverstripe

      - SS_DEFAULT_ADMIN_USERNAME=admin
      - SS_DEFAULT_ADMIN_PASSWORD=password

      - SS_ENVIRONMENT_TYPE=dev

    volumes:
      - ./docker-logs/phpfpm:/var/log/php-fpm
      # - ./docker-config/php/zz-xdebug.ini:/etc/php.d/16-xdebug.ini
      - ./src:/var/www/html

  php-cli:
    extends:
      service: php-fpm
    working_dir: /var/www/html/public
    command: gosu www-data bash

  db:
    image: mariadb:10.11
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  database:
