version: "3.7"

# env_file: .env

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  apachehttpd:
    image: twistedbytes/centos8-apachehttpd
    platform: linux/amd64
    networks:
      backend:
        aliases:
          - dockertest1.tbdocker.xyz
    # user: "${APP_USER_ID}:${APP_GROUP_ID}"
    volumes:
      # - ./docker-config/apache-vhosts:/etc/httpd/vhosts.d
      - ./test/logs/httpd:/var/log/httpd
      # - ./src/Silverstripe:/var/www/html/Silverstripe
      - ./test/html/public:/var/www/html/public
      # - ./run-on-start:/aa-run-on-start
    environment:
      - _TB_UIDGID_FROMDIR=/var/www/html/public
      # - _TB_UIDGID=1005:1005
      - _TB_TZ=${TIMEZONE}
    ports:
      - "127.0.0.1:${HTTP_PORT:-80}:80"
      - "127.0.0.1:${HTTPS_PORT:-443}:443"
    command:
      - /usr/sbin/httpd
      - -DFOREGROUND
