version: "3.7"

# env_file: .env

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  apachehttpd:
    extends:
      file: compose-services.yml
      service: apachehttpd
    networks:
      backend:
        aliases:
          - dockertest1.tbdocker.xyz
          - dockertest2.tbdocker.xyz
    user: "${APP_USER_ID}:${APP_GROUP_ID}"
    volumes:
      # - ./docker-config/apache-vhosts:/etc/httpd/vhosts.d
      - ./test/logs/httpd:/var/log/httpd
      # - ./src/Silverstripe:/var/www/html/Silverstripe
      - ./test/html/public:/var/www/html/public
    ports:
      - "127.0.0.1:${HTTP_PORT:-80}:80"
      - "127.0.0.1:${HTTPS_PORT:-443}:443"
    command:
      - /usr/sbin/httpd
      - -DFOREGROUND
